### ISSUE TITLE
Traer valores de archivo

### ISSUE THREAD

**Issue by AngieArlanti** [AngieArlanti/sia-tp2#4]
En la función main.m traer todos los datos necesarios de archivo:

- Traer inputs de terrain.csv
- Separar inputs de testeo y de aprendizaje (hay un criterio para hacerlo preguntar).
- Traer arquitectura de archivo.
- Traer etha de archivo.
- Traer función de activación de archivo.
- Traer acceptedError de archivo.

**Comment by santi698** [comment]
@AngieArlanti les parece si el archivo de configuración es un `.m`? Porque  leer un archivo de texto no parece muy sencillo

**Comment by santi698** [comment]
Y no entendí esto:
> - Separar inputs de testeo y de aprendizaje (hay un criterio para hacerlo preguntar).

**Comment by agophurmuz** [comment]
Respecto de Separar input de testeo y aprendizaje. Fíjate como está hecho el main.m .. necesitamos hacer el aprendizaje (train) con un grupo de inputs (inputs de aprendizaje) que tiene que ser distinto a los valores con los cuales hacemos la evaluación (inputs de testeo). Para esto tenemos que separar de los inputs dos grupos. Esto en realidad se hace con un criterio.. estaría bueno que lo averiguas. 
Después evaluar la network en los puntos de testeo y de aprendizaje y sacas los dos errores... estos se comparan para saber si hubo sobreentrenamiento.
